// Phase 6.5 validation fixtures — NOT part of the shipped app.
// Original prose written for this validation round (guaranteed not to
// appear in the real archive or any real live-search index), used to build
// controlled small/medium/large/full copied-coverage cases against the REAL
// user-submission-corpus matcher (lib/user-submission-matching.ts) via the
// real POST/GET /api/reports routes.

export const REFERENCE_TEXT = `Hydrothermal vent communities along the fictitious Kelmar Ridge spreading center have provided an unusually clear natural experiment in chemosynthetic succession following a documented eruptive event in the study region. Researchers returned to six previously mapped vent orifices at eighteen-month intervals across a five-year survey window, using a remotely operated vehicle equipped with a precision manipulator arm and paired temperature-conductivity probes to characterize the physical envelope surrounding each colonized structure. Tubeworm aggregations at the freshly resurfaced orifices were absent during the first post-eruption survey but had reached near-maximal areal coverage by the third revisit, a recovery trajectory considerably faster than comparable observations reported from other slow-spreading ridge segments.

Microbial mat coverage followed a distinct and reproducible successional pattern across all six orifices. Filamentous sulfur-oxidizing mats colonized bare basalt within the first observed interval, reaching peak coverage before tubeworm recruitment began in earnest, after which mat coverage declined sharply as the developing tubeworm bushes altered local fluid flow and substrate availability. The research team interpreted this decline as evidence of active ecosystem engineering by the tubeworms themselves, rather than a simple consequence of diffuse-flow chemistry drifting away from conditions favorable to the mat-forming taxa. Paired fluid chemistry samples supported this interpretation: hydrogen sulfide concentrations measured immediately adjacent to dense tubeworm bushes were consistently lower than concentrations measured at open, mat-dominated patches sampled during the same visit, despite both sample types being drawn from orifices with statistically indistinguishable vent-fluid endmember chemistry.

Amphipod and gastropod grazer densities within the tubeworm bushes rose steadily across the survey window, tracking the increasing structural complexity of the aggregations rather than tracking time since eruption directly. The authors note that this distinction matters for interpreting recovery trajectories at ridge segments where eruption timing is poorly constrained: structural complexity, not elapsed time alone, appears to be the more proximate driver of associated grazer community development in this system. A parallel manipulation, in which researchers experimentally cleared a subset of tubeworm bushes at three orifices, produced grazer recolonization curves that closely tracked the natural recovery observed elsewhere, lending further support to a structure-driven rather than a purely temporal explanation.

Genetic sampling of the dominant tubeworm population revealed limited differentiation among the six orifices despite their separation along nearly forty kilometers of ridge axis, consistent with a larval dispersal regime capable of maintaining regional connectivity across that distance at this spreading rate. The authors caution that this finding should not be generalized uncritically to faster-spreading ridge systems, where hydrographic conditions and larval duration constraints may differ substantially. Comparison with an archival tissue collection from a survey conducted at the same orifices nine years prior to the eruption showed no detectable shift in the dominant mitochondrial haplotype frequencies, suggesting that the post-eruption population was substantially reseeded from the same regional source population rather than colonized by a genetically distinct founder cohort arriving from elsewhere along the ridge.

Overall the study offers a rare, tightly time-constrained window into chemosynthetic ecosystem succession, and the authors argue that the observed sequence, sulfur-oxidizing mat dominance giving way to tubeworm-dominated structural complexity, which in turn reshapes local fluid chemistry and drives grazer community assembly, may represent a general successional template applicable to other slow-spreading vent systems recovering from a discrete disturbance event, pending confirmation from additional post-eruption survey series elsewhere.`;

export const REFERENCE_WORD_COUNT = REFERENCE_TEXT.split(/\s+/).filter(Boolean).length;

const words = REFERENCE_TEXT.split(/\s+/).filter(Boolean);

// A distinctive ~40-word span from the middle of paragraph 2.
export const SMALL_EXCERPT = words.slice(190, 230).join(" ");
// A distinctive ~200-word span spanning the end of paragraph 2 into paragraph 3.
export const MEDIUM_EXCERPT = words.slice(150, 350).join(" ");
// A distinctive ~500-word span covering most of paragraphs 2-4.
export const LARGE_EXCERPT = words.slice(60, 560).join(" ");

// Two REAL, genuinely open-access published abstracts (verbatim, fetched
// live from the real Europe PMC REST API on 2026-08-16), used only to
// exercise the REAL OpenAIRE + Europe PMC live-search pipeline with text
// that is actually confirmable against a real, findable published source.
export const KERNZA_ABSTRACT = `Kernza intermediate wheatgrass (Thinopyrum intermedium [Host] Barkworth & D.R. Dewey) is a novel dual-use perennial grain and forage crop with environmental and economic benefits for farmers. Perennial crop byproducts, such as Kernza straw, have been suggested as an alternative forage source in livestock systems. However, there is limited information on cattle performance offered Kernza straw. Therefore, our study assessed the performance of mature beef cows fed Kernza straw mixed with a haylage composed of alfalfa (Medicago sativa L.) and cool-season grasses. Grasses included orchardgrass (Dactylis glomerata L.), meadow fescue (Festuca pratensis L.) and Kentucky bluegrass (Poa pratensis L.). Two feeding trials conducted in two different years were performed with 36 pregnant Angus cows (Bos taurus) in six pens of six animals each in a completely randomized design with three replications. Dietary treatments included: (i) a 100% grass-alfalfa haylage (control), and (ii) a 50% Kernza straw - 50% grass-alfalfa haylage. Average daily gain was lower in the Kernza straw cows than in the control group (0.41 vs 0.92 kg day-1) in Trial 1 (P = 0.02) with no differences in Trial 2 (P = 0.13). Daily dry matter intake did not change in Trial 1 (P = 0.08), while for the cows offered Kernza straw it was reduced from 12.9 to 11.3 kg cow-1 day-1 in Trial 2 (P < 0.01). There were no changes in body condition among cows fed different diets in both trials (P > 0.05). Therefore, 50% Kernza straw can be successfully used in beef cow diets at least for 60 days without negative impacts on animal performance and potential economic and environmental benefits.`;
export const KERNZA_DOI = "10.1093/tas/txaf131";
export const KERNZA_PMCID = "PMC12967033";

export const CLATHRIN_ABSTRACT = `Clathrin-mediated endocytosis (CME) relies on the dynamic assembly and remodeling of clathrin coats to drive membrane curvature and vesicle formation at the plasma membrane. Although live-cell fluorescence microscopy has provided critical insights into the timing and molecular composition of endocytic events, directly linking the nanoscale lateral organization of clathrin coats to their three-dimensional progression in real time has remained challenging. Structural approaches such as electron microscopy provide detailed snapshots of clathrin architecture but are inherently static, whereas axial TIRF-based methods report membrane-proximal position with limited lateral resolution. Here, we introduce variable-angle total internal reflection fluorescence structured illumination microscopy (vaTIRF-SIM), a live-cell imaging strategy that integrates lateral super-resolution with dynamic axial sensitivity near the plasma membrane. By combining TIRF-SIM with controlled variation of the evanescent field penetration depth, vaTIRF-SIM enables simultaneous visualization of clathrin coat architecture and relative axial displacement with high spatial and temporal resolution. Applying this approach to de novo clathrin-coated pits reveals coordinated lateral growth and progressive axial advancement from early stages of pit formation through maturation, consistent with early curvature generation that intensifies over time. Extending this analysis to clathrin plaques uncovers two distinct plaque-associated endocytic behaviors: slowly maturing pits that originate at plaque peripheries and progress similarly to de novo pits and rapid plaque subdomain internalization events marked by accelerated axial progression. Together, these results establish vaTIRF-SIM as an approach that, for the first time, enables direct real-time coupling of nanoscale clathrin coat organization with axial progression during CME in living cells, demonstrated here in genome-edited SUM-159 cells expressing AP2-EGFP from the endogenous locus.`;
export const CLATHRIN_DOI = "10.1111/tra.70038";
export const CLATHRIN_PMCID = "PMC13282716";

export const ORIGINAL_TEXT = `The migratory behavior of a fictitious population of high-altitude nectarivorous bats on the slopes of the equally fictitious Serrindao volcanic range has fascinated the invented research team behind this validation passage, purely because no such bats, mountains, or research team exist anywhere in the real literature. This paragraph, and the two that follow, are composed specifically for a software validation exercise and are not derived from, quoted from, or paraphrased from any real published source, archive document, or web page. Any resemblance to real academic prose is intentional only insofar as the sentence structure should read naturally; the underlying claims, species, locations, and findings are fabricated for testing purposes only.

Because this text is deliberately invented, it should not match any entry in a real document archive, nor should it be discoverable through a live academic search across real scholarly databases, since no paper describing these specific invented bats or this specific invented mountain range could plausibly exist. A validation harness can therefore use this passage as a negative control: if a similarity system reports a nonzero match against either the private archive or a live external search for this exact text, that would indicate a false positive rather than a genuine textual correspondence, since the passage was authored from scratch for this single purpose and has never been published anywhere before this test run.

The remainder of this paragraph exists only to lengthen the passage to a more realistic submission size for testing purposes, repeating the same negative-control intent in slightly different words: this is original, unpublished, fabricated text written solely to confirm that neither the archive matcher nor the live academic search pipeline produces spurious matches against content that has no genuine source anywhere in either system.`;

export function paddedSubmission(excerpt, paddingLabel) {
  const paddingBefore = `${paddingLabel} A separate line of independent original commentary precedes the borrowed material below, written specifically to surround the embedded excerpt with clearly unrelated, freshly composed sentences about an entirely different subject so that the matcher's shingle windows have unambiguous non-matching context on both sides. This paragraph exists purely as structural padding for a validation exercise and describes nothing about vent ecology at all.`;
  const paddingAfter = `Separately, and again entirely unrelated to the passage above, this closing paragraph discusses an unrelated logistics topic: shipping container scheduling variance at a regional freight terminal over a six-month observation period, included here only to give the submitted document realistic surrounding length and additional non-matching padding text.`;
  return `${paddingBefore}\n\n${excerpt}\n\n${paddingAfter}`;
}
