/**
 * Regenerates lib/geonames-cities-data.ts from the GeoNames cities15000 dump.
 *
 *   1. Download https://download.geonames.org/export/dump/cities15000.zip
 *   2. unzip -> cities15000.txt
 *   3. node --import tsx tools/build-geonames-cities.ts path/to/cities15000.txt
 *
 * GeoNames data is licensed CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/).
 * We keep only: geonameid, display name, ISO 3166-1 alpha-2 country code (cross-
 * checked against lib/iso-3166-1-countries.ts), GeoNames admin1 code, population.
 * Rows whose country code is not an officially-assigned ISO alpha-2 (e.g. XK for
 * Kosovo) are dropped — residence country in this product is ISO-only.
 */
import fs from "node:fs";
import path from "node:path";

const srcTxt = process.argv[2];
if (!srcTxt || !fs.existsSync(srcTxt)) {
  console.error("usage: node --import tsx tools/build-geonames-cities.ts <cities15000.txt>");
  process.exit(1);
}
const repo = path.resolve(".");
const isoSrc = fs.readFileSync(path.join(repo, "lib", "iso-3166-1-countries.ts"), "utf8");
const isoAlpha2 = new Set([...isoSrc.matchAll(/alpha2:\s*"([A-Z]{2})"/g)].map((m) => m[1]));

type Row = { id: number; name: string; cc: string; admin1: string; pop: number };
const rows: Row[] = [];
let skippedNonIso = 0;
for (const line of fs.readFileSync(srcTxt, "utf8").split("\n")) {
  if (!line.trim()) continue;
  const f = line.split("\t");
  const id = Number(f[0]);
  const name = (f[1] || "").trim();
  const fclass = (f[6] || "").trim();
  const cc = (f[8] || "").trim().toUpperCase();
  const admin1 = (f[10] || "").trim().replace(/[\t\n]/g, "");
  const pop = Number(f[14] || 0);
  if (!Number.isInteger(id) || id <= 0 || !name || cc.length !== 2 || fclass !== "P") continue;
  if (name.includes("\t") || name.includes("\n")) continue;
  if (!isoAlpha2.has(cc)) {
    skippedNonIso += 1;
    continue;
  }
  rows.push({ id, name, cc, admin1, pop: Number.isFinite(pop) && pop > 0 ? pop : 0 });
}
rows.sort((a, b) => b.pop - a.pop || a.id - b.id);

const seen = new Set<number>();
for (const r of rows) {
  if (seen.has(r.id)) throw new Error(`duplicate geonameid ${r.id}`);
  seen.add(r.id);
}

const packed = rows.map((r) => `${r.id}\t${r.name}\t${r.cc}\t${r.admin1}\t${r.pop}`).join("\n");
const mb = (Buffer.byteLength(packed, "utf8") / 1024 / 1024).toFixed(1);
const escaped = packed.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const out = `// AUTO-GENERATED by tools/build-geonames-cities.ts from GeoNames cities15000
// (populated places, population >= 15,000).
// Source: https://download.geonames.org/export/dump/cities15000.zip
// License: CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/).
//
// Format: one row per line, TAB-separated:
//   geonameid \\t display name \\t ISO 3166-1 alpha-2 country \\t GeoNames admin1 code \\t population
// Sorted by population descending. Every country code is a valid ISO 3166-1
// alpha-2 (cross-checked against lib/iso-3166-1-countries.ts at generation time);
// non-ISO GeoNames codes (e.g. XK Kosovo) are dropped.
//
// SERVER-ONLY: this string is ~${mb} MB. It must never be imported into a client
// bundle — lib/geonames-cities.ts (its only importer) is server-only, and
// tests/account-identity-signup.test.mjs pins that no client module imports it.
export const GEONAMES_CITIES15000_TSV = \`${escaped}\`;
export const GEONAMES_CITIES15000_ROW_COUNT = ${rows.length};
`;

fs.writeFileSync(path.join(repo, "lib", "geonames-cities-data.ts"), out);
console.log(`wrote lib/geonames-cities-data.ts — ${rows.length} cities, ~${mb} MB packed, ${skippedNonIso} non-ISO rows dropped`);
